Numpy

NumPy is a fundamental library for scrinetific computing in Python . It provides supports for arrays and mathematics along with maths functions to operate on these data structures . 

In [ ]:
## let us create an array with numpy 

## i am going to create a 1D array

import numpy as np

arr1 =  np.array([1,2,3,4,5])   ## np.array() is a fucntion that helps us to creatw an array

print(arr1)
print(type(arr1))  ## nd means that it is an n dimension array 
print(arr1.shape)  ## whenever thewe is a single dimension there would be oly one number and comma blank



## whenever we work with single dimension array we dont need to provide any rows and columns 

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## let us create  a 2 dimensional array 

arr2 = np.array([1,2,3,4,5])
arr2.reshape([1,5])

# A single dimension array we can basically seee one braces opening and closing
# In two dimension array we can see two square brackets openng and closing like in this example 
# In three dimesnion array we would seee threee square brackets opening and closing.

##    THIS HOW YOU CAN ACTUAALY IDENTIFY THE DIMENISON OF AN ARRAY 

# NOW since i have reshaped this array into (1,5) i told i need to reshape this into 1 rows and 5 columns 
# if i would try to reshape it into (1,4) it will throw me an error WHY? bcz there are five elements



array([[1, 2, 3, 4, 5]])

In [ ]:
## now let us try to create this type of array directly 

arr2 = np.array([[1,2,3,4,5]])
print(arr2)
print(arr2.shape)

## so what did i do -- i created a nested list , and it got created as a SINGLE DIMENSION ARRAY 
## 1 ROW AND 5 COLUMNS

[[1 2 3 4 5]]
(1, 5)


In [ ]:
## now let us try to add more elements to it 
arr2 = np.array([[1,2,3,5] , [1,2,3,4]])

print(f"{arr2} \n arr_shape : {arr2.shape}")

## now i can see that this is a 2 dimensional array , 2 rows and 4 columns 
## and 2 square brackets opening and closing 


## 2D ARRAY

[[1 2 3 5]
 [1 2 3 4]] 
 arr_shape : (2, 4)


In [ ]:
###               let us go ahead and create arrays with some in built functions 

In [ ]:
#np.arange(0,10,2).reshape(1,5)


arr = np.arange(0,10,2)

print(f"{arr.reshape(1,5)} \n  {arr.reshape(5,1)}")


## so we can use an in built function np.arange to generate arrays 
## parameters -- ( start , stop , step ) 
## so i can also modify the kind of array that i want by using .reshape 

## so from (0,10,2) i know i will get 5 elements in this array,


## the difference in .reshape(5,1)  and .reshape(1,5) is 

## .reshape(1,5) -- 1 row, 5 columns -- it becomes a horizontal row vector -- row matrix
## .reshape(5,1) -- 5 rows , 1 column -- vertical column vector -- column matrix


# Reshape doesn’t change data, only its structure (rows × columns). Total elements must match.

[[0 2 4 6 8]] 
  [[0]
 [2]
 [4]
 [6]
 [8]]


In [ ]:
np.ones((3,4))  

## so np.ones() is an inbuilt function in numpy 
## It is used when you neeed an array filled with 1s quickly
## Examples :
## init weights in ML
## creating placeholder array


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.eye(3)
## eye = identity matrix
## 1s on diagonal and zeros everywheere else


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## ATTRIBUTES OF AN ARRAY


arr = np.array([[[1,2,3] , [4,5,6],[3,4,5]]])

print(arr)

## if i want arr shape (rows,columns)
print(f"Shape : {arr.shape}")

## if i want arr dimensions
print(f"Number of dimensions : {arr.ndim}")   # dim = no. of square brackets

## if i want arr size
print(f"Size(number of elements) : {arr.size}")

## if i want data type my arr hold
print(f"DataType : {arr.dtype}")

##Item size
print(f"Item Size(in bytes) : {arr.itemsize}")  # item size = memory used by ONE elem of the array



[[[1 2 3]
  [4 5 6]
  [3 4 5]]]
Shape : (1, 3, 3)
Number of dimensions : 3
Size(number of elements) : 9
DataType : int64
Item Size(in bytes) : 8


NUMPY VECTORIZED OPERATIONS 

In [42]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## elem wise addition
print("addition", arr1 + arr2)

## elem wise subtraction
print("substraction", arr2-arr1)


## elem wise multiplication
print("multiplication", arr1*arr2)

## elem wise division
print("division" , arr1/arr2)


addition [11 22 33 44 55]
substraction [ 9 18 27 36 45]
multiplication [ 10  40  90 160 250]
division [0.1 0.1 0.1 0.1 0.1]


UNIVERSAL FUNCTIONS

Means that some functions that applies to the entire array

In [45]:
arr = np.array([1,2,3,4])

## square root
print(np.sqrt(arr))

## exponential
print(np.exp(arr1))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))


[1.         1.41421356 1.73205081 2.        ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]


ARR SLICING AND INDEXING

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

## so we have a 2D array over here with  3 rows and 4 columns
## In order to access values we have to access in such a way that we focus on the indexes it can be the row or column index , index will always start with 0 


## let us try to access the very first value in first row and first column

print(arr[0][0]) # --> 1

## very last value
print(arr[2][2])

## Slicing

## arr[row_start : row_end , col_start : col_end ]
# both slices happen simultaneously 
# the part before commas --> rows
# the part after commas --> columns

print(arr[1:,2:]) 

print(arr[1:,3:])

print(arr[0:2,2:])




1
11
[[ 7  8]
 [11 12]]
[[ 8]
 [12]]
[[3 4]
 [7 8]]


In [55]:
## Modify array elements 

arr[0,0] = 100

print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [62]:
arr[1:] = 30
print(arr)

## by doing this ill be able to change every element in second and third row to 30

[[100   2   3   4]
 [ 30  30  30  30]
 [ 30  30  30  30]]


PRACTICAL APPLICATIONS


In [ ]:
### Statistical Concept

# NORMALIZATION
# normalization means -- to have mean = 0 and standard deviation = 1

In [66]:
data = np.array([1,2,3,4,5])

# calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

print(f"mean : {mean} , std : {std_dev}")

# NORMALIZE THE DATA
normalized_data = (data - mean) / std_dev
print(f"Normalized data : {normalized_data}")

mean : 3.0 , std : 1.4142135623730951
Normalized data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


How to Calculate 
* Mean
* Median
* Standard Deviation
* Variance 

In [69]:
data = np.array([1,2,3,4,5,6,7,8,8])

mean = np.mean(data)

median = np.median(data)



Std_Dev = np.std(data)

Var = np.var(data)

print(f"mean : {mean} , median :{median}, Std_Dev : {Std_Dev}, Variance : {Var}")


mean : 4.888888888888889 , median :5.0, Std_Dev : 2.4241582476968255, Variance : 5.876543209876543


PRACTICE QUESTIONS 


In [10]:
## ARRAY SLICING + MODIFICATION

import numpy as np 

arr = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]
])

## slice out this block  
# [[20,30],
#  [60,70]]

arr_slice = arr[0:2,1:3]

# Change ONLY the value 30 to 999 through the slice.

arr_slice[0,1] = 999

#Print the original array to show the change.


print(f"Sliced array : \n {arr_slice}  \n \n original_array : \n {arr}")

Sliced array : 
 [[ 20 999]
 [ 60  70]]  
 
 original_array : 
 [[ 10  20 999  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [21]:
## Vectorized ops + Boolean Filtering + aggregation

sales = np.array([120, 250, 300, 90, 400, 50])

# Do the following:

# Increase all sales by 10% using vectorized operation.

# Filter only the sales greater than 200.

# Print:

# the filtered values

# their sum

# their mean

# Checks: vectorization + boolean indexing + aggregations.

sales_increase = sales*1.10 

# sales greater than 200
sales_greater = sales[sales>200]

# sum , mean
sales_greater_sum = np.sum(sales_greater)

sales_greater_mean = np.mean(sales_greater)

print(f"Sales increased by 10% :  {sales_increase} \n \n Sales greater than 200 :  {sales_greater} \n Sum : {sales_greater_sum} \n Mean : {sales_greater_mean}")




Sales increased by 10% :  [132. 275. 330.  99. 440.  55.] 
 
 Sales greater than 200 :  [250 300 400] 
 Sum : 950 
 Mean : 316.6666666666667
